# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SendBeam.SendBeam
PackageVersion: 1.7.0
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: sendbeam.exe
    PortableCommandAlias: sendbeam
ReleaseDate: 2026-08-31
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Akshay7273/sendbeam/releases/download/v1.7.0/sendbeam-cli-windows-amd64.zip
    InstallerSha256: 14A1C3F27C88514AF6E2AAA3B27968BCBCEF8F1AB42604145CDA565D6420A081
  - Architecture: arm64
    InstallerUrl: https://github.com/Akshay7273/sendbeam/releases/download/v1.7.0/sendbeam-cli-windows-arm64.zip
    InstallerSha256: FBE28B2BEF8FF4D39A7E8A8CA8C05178589C246EB86DFB61A1926655F516D0F7
ManifestType: installer
ManifestVersion: 1.6.0
