# typed: false
# frozen_string_literal: true

# This file was generated by SendBeam Package Automation. DO NOT EDIT.
class Sendbeam < Formula
  desc "Secure, direct, peer-to-peer file transfer in your browser and terminal"
  homepage "https://omnitrix.space"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.6.0/sendbeam-cli-darwin-arm64.tar.gz"
      sha256 "149f2ddbd70a1dcaab92667e5cc1aa3d9688416e502cb1041c5b79926999c8b5"
    else
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.6.0/sendbeam-cli-darwin-amd64.tar.gz"
      sha256 "27ea31590cce12a2580b2938ecda0586bc9427be64c46b5cf5cbd67775150eb7"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.6.0/sendbeam-cli-linux-arm64.tar.gz"
      sha256 "3e50f298dd62c2af1eac1bd552e79a2f8a676e7f0205fa9791399fe74a11827f"
    else
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.6.0/sendbeam-cli-linux-amd64.tar.gz"
      sha256 "b2886f6c894cb5de53bb78823ed49761d0ef06532d8f1a390349ecb056c9f6ad"
    end
  end

  def install
    bin.install "sendbeam"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sendbeam --version")
  end
end
