# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SendBeam.SendBeam
PackageVersion: 1.9.0
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: sendbeam.exe
    PortableCommandAlias: sendbeam
ReleaseDate: 2026-09-07
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Akshay7273/sendbeam/releases/download/v1.9.0/sendbeam-cli-windows-amd64.zip
    InstallerSha256: A5063A9CFEEEA34376B933589F5841AA7991622FE565D40F65D9CBA1A0E5FD32
  - Architecture: arm64
    InstallerUrl: https://github.com/Akshay7273/sendbeam/releases/download/v1.9.0/sendbeam-cli-windows-arm64.zip
    InstallerSha256: FFA56BA894B631F30BC1CB842C93DFA326380DD74626BF5B120B6D975E7659CE
ManifestType: installer
ManifestVersion: 1.6.0
