package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

type PackageHashes struct {
	DarwinArm64  string
	DarwinAmd64  string
	LinuxArm64   string
	LinuxAmd64   string
	WindowsArm64 string
	WindowsAmd64 string
}

func main() {
	var (
		versionFlag  = flag.String("version", "", "product version (e.g. 1.7.0)")
		tagFlag      = flag.String("tag", "", "release tag (e.g. v1.7.0)")
		sumsFlag     = flag.String("sums", "SHA256SUMS.txt", "path to SHA256SUMS.txt manifest")
		repoFlag     = flag.String("repo", "Akshay7273/sendbeam", "GitHub repository owner/name")
		homepageFlag = flag.String("homepage", "https://omnitrix.space", "product homepage URL")
		outDirFlag   = flag.String("out-dir", "packaging", "output directory for packaging manifests")
		syncRootFlag = flag.Bool("sync-root", true, "sync Formula/sendbeam.rb and bucket/sendbeam.json at repo root")
		validateFlag = flag.Bool("validate", false, "validate existing manifests against SHA256SUMS.txt without writing")
		dateFlag     = flag.String("release-date", "", "release date in YYYY-MM-DD format (defaults to current UTC date)")
	)
	flag.Parse()

	if *versionFlag == "" && *tagFlag == "" {
		fmt.Fprintf(os.Stderr, "error: either --version or --tag is required\n")
		os.Exit(1)
	}

	version := *versionFlag
	tag := *tagFlag
	if version == "" {
		version = strings.TrimPrefix(tag, "v")
	}
	if tag == "" {
		tag = "v" + version
	}

	relDate := *dateFlag
	if relDate == "" {
		relDate = time.Now().UTC().Format("2006-01-02")
	}

	hashes, err := loadPackageHashes(*sumsFlag)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error loading checksums from %s: %v\n", *sumsFlag, err)
		os.Exit(1)
	}

	if *validateFlag {
		if err := validateManifests(*outDirFlag, *syncRootFlag, version, tag, *repoFlag, hashes); err != nil {
			fmt.Fprintf(os.Stderr, "validation failed: %v\n", err)
			os.Exit(1)
		}
		fmt.Println("All package manager manifests are valid and match SHA256SUMS.txt.")
		return
	}

	if err := generateAllManifests(*outDirFlag, *syncRootFlag, version, tag, *repoFlag, *homepageFlag, relDate, hashes); err != nil {
		fmt.Fprintf(os.Stderr, "error generating manifests: %v\n", err)
		os.Exit(1)
	}

	// Validate after generation
	if err := validateManifests(*outDirFlag, *syncRootFlag, version, tag, *repoFlag, hashes); err != nil {
		fmt.Fprintf(os.Stderr, "post-generation validation failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated and validated package manager manifests for %s (tag %s).\n", version, tag)
}

func loadPackageHashes(sumsPath string) (PackageHashes, error) {
	file, err := os.Open(sumsPath)
	if err != nil {
		return PackageHashes{}, err
	}
	defer file.Close()

	var hashes PackageHashes
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		hash := strings.ToLower(fields[0])
		if len(hash) != 64 {
			continue
		}
		name := strings.TrimPrefix(strings.Join(fields[1:], " "), "*")
		name = strings.TrimSpace(name)

		switch name {
		case "sendbeam-cli-darwin-arm64.tar.gz":
			hashes.DarwinArm64 = hash
		case "sendbeam-cli-darwin-amd64.tar.gz":
			hashes.DarwinAmd64 = hash
		case "sendbeam-cli-linux-arm64.tar.gz":
			hashes.LinuxArm64 = hash
		case "sendbeam-cli-linux-amd64.tar.gz":
			hashes.LinuxAmd64 = hash
		case "sendbeam-cli-windows-arm64.zip":
			hashes.WindowsArm64 = hash
		case "sendbeam-cli-windows-amd64.zip":
			hashes.WindowsAmd64 = hash
		}
	}

	if err := scanner.Err(); err != nil {
		return PackageHashes{}, err
	}

	var missing []string
	if hashes.DarwinArm64 == "" {
		missing = append(missing, "sendbeam-cli-darwin-arm64.tar.gz")
	}
	if hashes.DarwinAmd64 == "" {
		missing = append(missing, "sendbeam-cli-darwin-amd64.tar.gz")
	}
	if hashes.LinuxArm64 == "" {
		missing = append(missing, "sendbeam-cli-linux-arm64.tar.gz")
	}
	if hashes.LinuxAmd64 == "" {
		missing = append(missing, "sendbeam-cli-linux-amd64.tar.gz")
	}
	if hashes.WindowsArm64 == "" {
		missing = append(missing, "sendbeam-cli-windows-arm64.zip")
	}
	if hashes.WindowsAmd64 == "" {
		missing = append(missing, "sendbeam-cli-windows-amd64.zip")
	}

	if len(missing) > 0 {
		return hashes, fmt.Errorf("missing hashes in %s for: %s", sumsPath, strings.Join(missing, ", "))
	}

	return hashes, nil
}

func generateHomebrewFormula(version, tag, repo, homepage string, hashes PackageHashes) string {
	return fmt.Sprintf(`# typed: false
# frozen_string_literal: true

# This file was generated by SendBeam Package Automation. DO NOT EDIT.
class Sendbeam < Formula
  desc "Secure, direct, peer-to-peer file transfer in your browser and terminal"
  homepage "%s"
  version "%s"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/%s/releases/download/%s/sendbeam-cli-darwin-arm64.tar.gz"
      sha256 "%s"
    else
      url "https://github.com/%s/releases/download/%s/sendbeam-cli-darwin-amd64.tar.gz"
      sha256 "%s"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/%s/releases/download/%s/sendbeam-cli-linux-arm64.tar.gz"
      sha256 "%s"
    else
      url "https://github.com/%s/releases/download/%s/sendbeam-cli-linux-amd64.tar.gz"
      sha256 "%s"
    end
  end

  def install
    bin.install "sendbeam"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sendbeam --version")
  end
end
`, homepage, version, repo, tag, hashes.DarwinArm64, repo, tag, hashes.DarwinAmd64, repo, tag, hashes.LinuxArm64, repo, tag, hashes.LinuxAmd64)
}

func generateScoopManifest(version, tag, repo, homepage string, hashes PackageHashes) (string, error) {
	manifest := map[string]interface{}{
		"version":     version,
		"description": "Secure, direct, peer-to-peer file transfer in your browser and terminal",
		"homepage":    homepage,
		"license":     "MIT",
		"architecture": map[string]interface{}{
			"64bit": map[string]string{
				"url":  fmt.Sprintf("https://github.com/%s/releases/download/%s/sendbeam-cli-windows-amd64.zip", repo, tag),
				"hash": hashes.WindowsAmd64,
			},
			"arm64": map[string]string{
				"url":  fmt.Sprintf("https://github.com/%s/releases/download/%s/sendbeam-cli-windows-arm64.zip", repo, tag),
				"hash": hashes.WindowsArm64,
			},
		},
		"bin":      "sendbeam.exe",
		"checkver": "github",
		"autoupdate": map[string]interface{}{
			"architecture": map[string]interface{}{
				"64bit": map[string]string{
					"url": fmt.Sprintf("https://github.com/%s/releases/download/v$version/sendbeam-cli-windows-amd64.zip", repo),
				},
				"arm64": map[string]string{
					"url": fmt.Sprintf("https://github.com/%s/releases/download/v$version/sendbeam-cli-windows-arm64.zip", repo),
				},
			},
			"hash": map[string]string{
				"url":   fmt.Sprintf("https://github.com/%s/releases/download/v$version/SHA256SUMS.txt", repo),
				"regex": "$sha256\\s+\\*?$basename",
			},
		},
	}

	buf := new(bytes.Buffer)
	enc := json.NewEncoder(buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "    ")
	if err := enc.Encode(manifest); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func generateWinGetVersion(version string) string {
	return fmt.Sprintf(`# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: SendBeam.SendBeam
PackageVersion: %s
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
`, version)
}

func generateWinGetInstaller(version, tag, repo, relDate string, hashes PackageHashes) string {
	return fmt.Sprintf(`# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SendBeam.SendBeam
PackageVersion: %s
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: sendbeam.exe
    PortableCommandAlias: sendbeam
ReleaseDate: %s
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/%s/releases/download/%s/sendbeam-cli-windows-amd64.zip
    InstallerSha256: %s
  - Architecture: arm64
    InstallerUrl: https://github.com/%s/releases/download/%s/sendbeam-cli-windows-arm64.zip
    InstallerSha256: %s
ManifestType: installer
ManifestVersion: 1.6.0
`, version, relDate, repo, tag, strings.ToUpper(hashes.WindowsAmd64), repo, tag, strings.ToUpper(hashes.WindowsArm64))
}

func generateWinGetLocale(version, homepage, repo string) string {
	return fmt.Sprintf(`# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: SendBeam.SendBeam
PackageVersion: %s
PackageLocale: en-US
Publisher: Akshay
PublisherUrl: https://github.com/Akshay7273
PublisherSupportUrl: https://github.com/%s/issues
PackageName: SendBeam
PackageUrl: %s
License: MIT
LicenseUrl: https://github.com/%s/blob/main/LICENSE
ShortDescription: Secure, direct, peer-to-peer file transfer in your browser and terminal
Description: SendBeam is an open-source, peer-to-peer file transfer tool with end-to-end encryption, QR code pairing, trusted mesh pairing, and wire privacy.
Tags:
  - p2p
  - file-transfer
  - webrtc
  - encryption
  - cli
ManifestType: defaultLocale
ManifestVersion: 1.6.0
`, version, repo, homepage, repo)
}

func generateAURPKGBUILD(version, tag, repo, homepage string, hashes PackageHashes) string {
	return fmt.Sprintf(`# Maintainer: Akshay <https://github.com/Akshay7273/sendbeam>
# Generated by SendBeam Package Automation. DO NOT EDIT.
pkgname=sendbeam-bin
pkgver=%s
pkgrel=1
pkgdesc="Secure, direct, peer-to-peer file transfer in your browser and terminal"
arch=('x86_64' 'aarch64')
url="%s"
license=('MIT')
provides=('sendbeam')
conflicts=('sendbeam')

source_x86_64=("https://github.com/%s/releases/download/%s/sendbeam-cli-linux-amd64.tar.gz")
source_aarch64=("https://github.com/%s/releases/download/%s/sendbeam-cli-linux-arm64.tar.gz")

sha256sums_x86_64=('%s')
sha256sums_aarch64=('%s')

package() {
  install -Dm755 "${srcdir}/sendbeam" "${pkgdir}/usr/bin/sendbeam"
  install -Dm644 "${srcdir}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
  install -Dm644 "${srcdir}/README.md" "${pkgdir}/usr/share/doc/${pkgname}/README.md"
}
`, version, homepage, repo, tag, repo, tag, hashes.LinuxAmd64, hashes.LinuxArm64)
}

func generateAURSRCINFO(version, tag, repo, homepage string, hashes PackageHashes) string {
	return fmt.Sprintf(`pkgbase = sendbeam-bin
	pkgdesc = Secure, direct, peer-to-peer file transfer in your browser and terminal
	pkgver = %s
	pkgrel = 1
	url = %s
	arch = x86_64
	arch = aarch64
	license = MIT
	provides = sendbeam
	conflicts = sendbeam
	source_x86_64 = https://github.com/%s/releases/download/%s/sendbeam-cli-linux-amd64.tar.gz
	sha256sums_x86_64 = %s
	source_aarch64 = https://github.com/%s/releases/download/%s/sendbeam-cli-linux-arm64.tar.gz
	sha256sums_aarch64 = %s

pkgname = sendbeam-bin
`, version, homepage, repo, tag, hashes.LinuxAmd64, repo, tag, hashes.LinuxArm64)
}

func generateAllManifests(outDir string, syncRoot bool, version, tag, repo, homepage, relDate string, hashes PackageHashes) error {
	// Homebrew formula
	brewFormula := generateHomebrewFormula(version, tag, repo, homepage, hashes)
	brewDir := filepath.Join(outDir, "homebrew", "Formula")
	if err := os.MkdirAll(brewDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(brewDir, "sendbeam.rb"), []byte(brewFormula), 0644); err != nil {
		return err
	}
	if syncRoot {
		if err := os.MkdirAll("Formula", 0755); err != nil {
			return err
		}
		if err := os.WriteFile("Formula/sendbeam.rb", []byte(brewFormula), 0644); err != nil {
			return err
		}
	}

	// Scoop manifest
	scoopManifest, err := generateScoopManifest(version, tag, repo, homepage, hashes)
	if err != nil {
		return err
	}
	scoopDir := filepath.Join(outDir, "scoop")
	if err := os.MkdirAll(scoopDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(scoopDir, "sendbeam.json"), []byte(scoopManifest), 0644); err != nil {
		return err
	}
	if syncRoot {
		if err := os.MkdirAll("bucket", 0755); err != nil {
			return err
		}
		if err := os.WriteFile("bucket/sendbeam.json", []byte(scoopManifest), 0644); err != nil {
			return err
		}
	}

	// WinGet manifests
	wingetVer := generateWinGetVersion(version)
	wingetInst := generateWinGetInstaller(version, tag, repo, relDate, hashes)
	wingetLoc := generateWinGetLocale(version, homepage, repo)

	wingetVersionDir := filepath.Join(outDir, "winget", "manifests", "s", "SendBeam", "SendBeam", version)
	if err := os.MkdirAll(wingetVersionDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(wingetVersionDir, "SendBeam.SendBeam.yaml"), []byte(wingetVer), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(wingetVersionDir, "SendBeam.SendBeam.installer.yaml"), []byte(wingetInst), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(wingetVersionDir, "SendBeam.SendBeam.locale.en-US.yaml"), []byte(wingetLoc), 0644); err != nil {
		return err
	}

	// Top-level winget template
	wingetTopDir := filepath.Join(outDir, "winget")
	if err := os.WriteFile(filepath.Join(wingetTopDir, "SendBeam.SendBeam.yaml"), []byte(wingetVer), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(wingetTopDir, "SendBeam.SendBeam.installer.yaml"), []byte(wingetInst), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(wingetTopDir, "SendBeam.SendBeam.locale.en-US.yaml"), []byte(wingetLoc), 0644); err != nil {
		return err
	}

	// AUR PKGBUILD and .SRCINFO
	aurPKGBUILD := generateAURPKGBUILD(version, tag, repo, homepage, hashes)
	aurSRCINFO := generateAURSRCINFO(version, tag, repo, homepage, hashes)

	aurDir := filepath.Join(outDir, "aur")
	if err := os.MkdirAll(aurDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(aurDir, "PKGBUILD"), []byte(aurPKGBUILD), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(aurDir, ".SRCINFO"), []byte(aurSRCINFO), 0644); err != nil {
		return err
	}

	return nil
}

func validateManifests(outDir string, syncRoot bool, version, tag, repo string, hashes PackageHashes) error {
	// Validate Homebrew
	brewPaths := []string{filepath.Join(outDir, "homebrew", "Formula", "sendbeam.rb")}
	if syncRoot {
		brewPaths = append(brewPaths, "Formula/sendbeam.rb")
	}
	for _, p := range brewPaths {
		data, err := os.ReadFile(p)
		if err != nil {
			return fmt.Errorf("reading brew formula %s: %w", p, err)
		}
		content := string(data)
		if !strings.Contains(content, fmt.Sprintf("version \"%s\"", version)) {
			return fmt.Errorf("%s: version does not match %s", p, version)
		}
		if !strings.Contains(content, hashes.DarwinArm64) {
			return fmt.Errorf("%s: missing darwin-arm64 hash %s", p, hashes.DarwinArm64)
		}
		if !strings.Contains(content, hashes.DarwinAmd64) {
			return fmt.Errorf("%s: missing darwin-amd64 hash %s", p, hashes.DarwinAmd64)
		}
		if !strings.Contains(content, hashes.LinuxArm64) {
			return fmt.Errorf("%s: missing linux-arm64 hash %s", p, hashes.LinuxArm64)
		}
		if !strings.Contains(content, hashes.LinuxAmd64) {
			return fmt.Errorf("%s: missing linux-amd64 hash %s", p, hashes.LinuxAmd64)
		}
	}

	// Validate Scoop
	scoopPaths := []string{filepath.Join(outDir, "scoop", "sendbeam.json")}
	if syncRoot {
		scoopPaths = append(scoopPaths, "bucket/sendbeam.json")
	}
	for _, p := range scoopPaths {
		data, err := os.ReadFile(p)
		if err != nil {
			return fmt.Errorf("reading scoop manifest %s: %w", p, err)
		}
		var manifest struct {
			Version      string `json:"version"`
			Architecture struct {
				Bit64 struct {
					URL  string `json:"url"`
					Hash string `json:"hash"`
				} `json:"64bit"`
				Arm64 struct {
					URL  string `json:"url"`
					Hash string `json:"hash"`
				} `json:"arm64"`
			} `json:"architecture"`
			Bin string `json:"bin"`
		}
		if err := json.Unmarshal(data, &manifest); err != nil {
			return fmt.Errorf("%s is invalid JSON: %w", p, err)
		}
		if manifest.Version != version {
			return fmt.Errorf("%s: expected version %s, got %s", p, version, manifest.Version)
		}
		if manifest.Architecture.Bit64.Hash != hashes.WindowsAmd64 {
			return fmt.Errorf("%s: 64bit hash mismatch (expected %s, got %s)", p, hashes.WindowsAmd64, manifest.Architecture.Bit64.Hash)
		}
		if manifest.Architecture.Arm64.Hash != hashes.WindowsArm64 {
			return fmt.Errorf("%s: arm64 hash mismatch (expected %s, got %s)", p, hashes.WindowsArm64, manifest.Architecture.Arm64.Hash)
		}
		if manifest.Bin != "sendbeam.exe" {
			return fmt.Errorf("%s: expected bin sendbeam.exe, got %s", p, manifest.Bin)
		}
	}

	// Validate WinGet
	wingetVersionPath := filepath.Join(outDir, "winget", "manifests", "s", "SendBeam", "SendBeam", version)
	wingetFiles := []string{
		filepath.Join(wingetVersionPath, "SendBeam.SendBeam.yaml"),
		filepath.Join(wingetVersionPath, "SendBeam.SendBeam.installer.yaml"),
		filepath.Join(wingetVersionPath, "SendBeam.SendBeam.locale.en-US.yaml"),
	}
	for _, f := range wingetFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("reading winget file %s: %w", f, err)
		}
		content := string(data)
		if !strings.Contains(content, fmt.Sprintf("PackageVersion: %s", version)) {
			return fmt.Errorf("%s: missing PackageVersion %s", f, version)
		}
		if strings.HasSuffix(f, ".installer.yaml") {
			if !strings.Contains(content, strings.ToUpper(hashes.WindowsAmd64)) {
				return fmt.Errorf("%s: missing uppercase windows-amd64 hash %s", f, strings.ToUpper(hashes.WindowsAmd64))
			}
			if !strings.Contains(content, strings.ToUpper(hashes.WindowsArm64)) {
				return fmt.Errorf("%s: missing uppercase windows-arm64 hash %s", f, strings.ToUpper(hashes.WindowsArm64))
			}
		}
	}

	// Validate AUR
	aurPKGBUILDPath := filepath.Join(outDir, "aur", "PKGBUILD")
	aurData, err := os.ReadFile(aurPKGBUILDPath)
	if err != nil {
		return fmt.Errorf("reading AUR PKGBUILD %s: %w", aurPKGBUILDPath, err)
	}
	aurContent := string(aurData)
	if !strings.Contains(aurContent, fmt.Sprintf("pkgver=%s", version)) {
		return fmt.Errorf("%s: missing pkgver=%s", aurPKGBUILDPath, version)
	}
	if !strings.Contains(aurContent, hashes.LinuxAmd64) {
		return fmt.Errorf("%s: missing x86_64 hash %s", aurPKGBUILDPath, hashes.LinuxAmd64)
	}
	if !strings.Contains(aurContent, hashes.LinuxArm64) {
		return fmt.Errorf("%s: missing aarch64 hash %s", aurPKGBUILDPath, hashes.LinuxArm64)
	}

	aurSRCINFOPath := filepath.Join(outDir, "aur", ".SRCINFO")
	srcinfoData, err := os.ReadFile(aurSRCINFOPath)
	if err != nil {
		return fmt.Errorf("reading AUR .SRCINFO %s: %w", aurSRCINFOPath, err)
	}
	srcinfoContent := string(srcinfoData)
	pkgverRe := regexp.MustCompile(`\bpkgver\s*=\s*` + regexp.QuoteMeta(version))
	if !pkgverRe.MatchString(srcinfoContent) {
		return fmt.Errorf("%s: missing pkgver = %s", aurSRCINFOPath, version)
	}
	if !strings.Contains(srcinfoContent, hashes.LinuxAmd64) {
		return fmt.Errorf("%s: missing x86_64 hash %s", aurSRCINFOPath, hashes.LinuxAmd64)
	}
	if !strings.Contains(srcinfoContent, hashes.LinuxArm64) {
		return fmt.Errorf("%s: missing aarch64 hash %s", aurSRCINFOPath, hashes.LinuxArm64)
	}

	return nil
}
