# typed: false
# frozen_string_literal: true

# This file was generated by SendBeam Package Automation. DO NOT EDIT.
class Sendbeam < Formula
  desc "Secure, direct, peer-to-peer file transfer in your browser and terminal"
  homepage "https://omnitrix.space"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.7.0/sendbeam-cli-darwin-arm64.tar.gz"
      sha256 "cc778a6aa8445129710bf83cb1557840c16453a4339e383c7af2551f00a923f1"
    else
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.7.0/sendbeam-cli-darwin-amd64.tar.gz"
      sha256 "52af7be301b9d2a927ea42799619a538bfaaf581385ef7512444d81fef5fcfde"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.7.0/sendbeam-cli-linux-arm64.tar.gz"
      sha256 "002c09880bde45ca6a845c6f17bf459df253f534e976ef573b802b0e26db6898"
    else
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.7.0/sendbeam-cli-linux-amd64.tar.gz"
      sha256 "02581557d250eb15268c018633d9ac9b8cadb7d99440986a8ff4daa63d036385"
    end
  end

  def install
    bin.install "sendbeam"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sendbeam --version")
  end
end
