# typed: false
# frozen_string_literal: true

# This file was generated by SendBeam Package Automation. DO NOT EDIT.
class Sendbeam < Formula
  desc "Secure, direct, peer-to-peer file transfer in your browser and terminal"
  homepage "https://omnitrix.space"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.9.0/sendbeam-cli-darwin-arm64.tar.gz"
      sha256 "30e7fc90a3749037220273a605691873e7421791dfbda46d93c87e87d3bf8408"
    else
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.9.0/sendbeam-cli-darwin-amd64.tar.gz"
      sha256 "95af245475d15f23a7ec4fb33f80bed1868445a84bf39a20e6dc26799cf7bcda"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.9.0/sendbeam-cli-linux-arm64.tar.gz"
      sha256 "c229471c18159f3e5f3f8a402935aab404deb062765538f0448929b1ca4364ab"
    else
      url "https://github.com/Akshay7273/sendbeam/releases/download/v1.9.0/sendbeam-cli-linux-amd64.tar.gz"
      sha256 "fc251b378bcc581074a5aaa505ea9b89b38c4c4b8a016618f3ffab7e7f95f6b5"
    end
  end

  def install
    bin.install "sendbeam"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sendbeam --version")
  end
end
