# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SendBeam.SendBeam
PackageVersion: 1.8.0
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: sendbeam.exe
    PortableCommandAlias: sendbeam
ReleaseDate: 2026-09-04
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Akshay7273/sendbeam/releases/download/v1.8.0/sendbeam-cli-windows-amd64.zip
    InstallerSha256: 354E23D25BCC7A696770141F0ACD98D2EC1F9F96B1EB720E383D993F813CBA03
  - Architecture: arm64
    InstallerUrl: https://github.com/Akshay7273/sendbeam/releases/download/v1.8.0/sendbeam-cli-windows-arm64.zip
    InstallerSha256: 101C6C5F8BA955E9003A6AD504E72F85001B7674317A11B20E9CB793C3980138
ManifestType: installer
ManifestVersion: 1.6.0
