package wire

import (
	"strings"
	"testing"
)

// V20-PR06: text/link handoffs ride the existing transfer protocol as a typed,
// size-bounded content envelope on the manifest. These are the wire-format
// regression tests: unknown kinds fail, handoffs must be exactly one small
// file, and the exact JSON byte layout must match the TypeScript twin.
func handoffEntry(size int64) FileEntry {
	const blockSize = int64(8)
	blocks := int64(0)
	if size > 0 {
		blocks = (size-1)/blockSize + 1
	}
	return FileEntry{Idx: 0, Name: "text.txt", Size: size, Mime: "text/plain; charset=utf-8",
		LastModified: 5, BlockSize: int(blockSize), Blocks: int(blocks), FileDigest: "ab"}
}

func TestValidateManifestRejectsUnknownContentKind(t *testing.T) {
	m := NewManifest([]FileEntry{handoffEntry(9)}, 9)
	m.ContentKind = "audio"
	if _, err := ValidateManifest(*m); err == nil {
		t.Fatal("ValidateManifest accepted unknown contentKind")
	}
}

func TestValidateManifestHandoffRequiresSingleFile(t *testing.T) {
	m := NewManifest([]FileEntry{handoffEntry(9), handoffEntry(9)}, 18)
	m.ContentKind = ContentKindText
	if _, err := ValidateManifest(*m); err == nil {
		t.Fatal("ValidateManifest accepted a multi-file text handoff")
	}
}

func TestValidateManifestHandoffSizeBounds(t *testing.T) {
	for _, tc := range []struct {
		name string
		size int64
		ok   bool
	}{
		{"zero bytes rejected", 0, false},
		{"one byte accepted", 1, true},
		{"cap accepted", MaxHandoffBytes, true},
		{"cap plus one rejected", MaxHandoffBytes + 1, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			m := NewManifest([]FileEntry{handoffEntry(tc.size)}, tc.size)
			m.ContentKind = ContentKindText
			_, err := ValidateManifest(*m)
			if tc.ok && err != nil {
				t.Fatalf("expected ok, got %v", err)
			}
			if !tc.ok && err == nil {
				t.Fatal("expected rejection, got ok")
			}
		})
	}
}

func TestValidateManifestLinkHandoff(t *testing.T) {
	m := NewManifest([]FileEntry{{
		Idx: 0, Name: "link.txt", Size: 19, Mime: "text/plain; charset=utf-8",
		LastModified: 5, BlockSize: 32, Blocks: 1, FileDigest: "cd",
	}}, 19)
	m.ContentKind = ContentKindLink
	if _, err := ValidateManifest(*m); err != nil {
		t.Fatalf("valid link handoff rejected: %v", err)
	}
}

func TestEncodeControlManifestWithContentKind(t *testing.T) {
	m := NewManifest([]FileEntry{{
		Idx: 0, Name: "a.txt", Size: 5, Mime: "text/plain; charset=utf-8",
		LastModified: 5, BlockSize: 8, Blocks: 1, FileDigest: "ab",
	}}, 5)
	m.ContentKind = ContentKindText
	got, err := EncodeControl(m)
	if err != nil {
		t.Fatal(err)
	}
	want := `{"type":2,"contentKind":"text","files":[{"idx":0,"name":"a.txt","size":5,"mime":"text/plain; charset=utf-8","lastModified":5,"blockSize":8,"blocks":1,"fileDigest":"ab"}],"totalSize":5}`
	if string(got) != want {
		t.Fatalf("manifest bytes differ:\n got: %s\nwant: %s", got, want)
	}
}

func TestDecodeControlManifestPreservesContentKind(t *testing.T) {
	raw := `{"type":2,"contentKind":"link","files":[{"idx":0,"name":"link.txt","size":19,"mime":"text/plain; charset=utf-8","lastModified":5,"blockSize":32,"blocks":1,"fileDigest":"cd"}],"totalSize":19}`
	msg, err := DecodeControl([]byte(raw))
	if err != nil {
		t.Fatal(err)
	}
	m, ok := msg.(*Manifest)
	if !ok {
		t.Fatalf("decoded to %T, want *Manifest", msg)
	}
	if m.ContentKind != ContentKindLink {
		t.Fatalf("contentKind = %q, want %q", m.ContentKind, ContentKindLink)
	}
	if _, err := ValidateManifest(*m); err != nil {
		t.Fatalf("decoded manifest failed validation: %v", err)
	}
}

func TestManifestFingerprintCoversContentKind(t *testing.T) {
	a := NewManifest([]FileEntry{handoffEntry(9)}, 9)
	b := NewManifest([]FileEntry{handoffEntry(9)}, 9)
	b.ContentKind = ContentKindText
	fa, err := ManifestFingerprint(*a)
	if err != nil {
		t.Fatal(err)
	}
	fb, err := ManifestFingerprint(*b)
	if err != nil {
		t.Fatal(err)
	}
	if fa == fb {
		t.Fatal("fingerprint ignores contentKind: file and handoff manifests collide")
	}
}

func TestContentKindConstants(t *testing.T) {
	if !IsHandoffKind(ContentKindText) || !IsHandoffKind(ContentKindLink) {
		t.Fatal("text/link must be handoff kinds")
	}
	if IsHandoffKind("") || IsHandoffKind(strings.ToUpper(ContentKindText)) {
		t.Fatal("empty/upper-case kinds must not match")
	}
}

// V20-PR06: exact wire bytes for a handoff manifest — pins Go/TS parity for the
// contentKind envelope (the same fixture is generated by the TS differential
// suite as ctrl_handoff_manifest_text).
func TestHandoffManifestExactBytes(t *testing.T) {
	m := &Manifest{
		Type:        FrameManifest,
		TransferID:  "handoff-text-00000000",
		ContentKind: ContentKindText,
		Files:       []FileEntry{{Idx: 0, Name: "text.txt", Size: 13, Mime: "text/plain; charset=utf-8", LastModified: 1700000000000, BlockSize: 65536, Blocks: 1, FileDigest: strings.Repeat("1", 64)}},
		TotalSize:   13,
	}
	enc, err := EncodeControl(*m)
	if err != nil {
		t.Fatal(err)
	}
	want := `{"type":2,"transferId":"handoff-text-00000000","contentKind":"text","files":[{"idx":0,"name":"text.txt","size":13,"mime":"text/plain; charset=utf-8","lastModified":1700000000000,"blockSize":65536,"blocks":1,"fileDigest":"` + strings.Repeat("1", 64) + `"}],"totalSize":13}`
	if string(enc) != want {
		t.Fatalf("handoff manifest bytes changed:\n got %s\nwant %s", enc, want)
	}
	// The round trip preserves the kind.
	dec, err := DecodeControl(enc)
	if err != nil {
		t.Fatal(err)
	}
	if dec.(*Manifest).ContentKind != ContentKindText {
		t.Fatal("decoded manifest lost contentKind")
	}
}

// V20-PR06: the handoff capability must be a stable, non-empty feature string.
func TestHandoffCapability(t *testing.T) {
	if HandoffCapability == "" {
		t.Fatal("HandoffCapability must not be empty")
	}
	if HandoffCapability != "handoff" {
		t.Fatalf("HandoffCapability = %q", HandoffCapability)
	}
}
